# Update with your Bridge's IP address
BRIDGE_IP: '192.168.86.39'

# Update with your Bridge's username
BRIDGE_USERNAME: 'nnE-bHVray8MWFhOesnuK6zOQ-GF0jOnf-SsQncK'

# Update with your light IDs
LIGHTS:
  - 1
  - 2

# If you want your lights to be different colors, set to True
MULTICOLOR: true
